# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60aa043a13b108a6b405a02c6139da5b0527d0b5f8f4c9f934bbc07c8d2f48e3cf851ded916a796911a83d3450ebe99d0743c285ec1181a580e03bda3133ba7e

test:
  secret_key_base: a181cdf08d80eddae536bcaf54046bbed560b89fdcfa25b92d8c4c218075eb0d99f1ebd5bfb406b19dc8e237f4cfa0eceb9b504a951ad6c7d072272622a9700d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
